defaults:     # 这里在指定文件夹中的内容
  - _self_
  - task: gfnft_voicecraft
  - device: gpu
  - hydra: default

seed: 27
save_dir: "runs/"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  project: "GFN-FT-VoiceCraft-sampling-${task.name}"
  save_dir: ${save_dir}
  offline: False