wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.47.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736252959.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 33
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      - 75
      - 98
      - 103
      - 105
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.6
      6: 4.47.1
      8:
      - 5
      13: linux-x86_64
